#include <gtest/gtest.h>
#include <ftxmodel/abstract_item_model.hpp>
#include <ftxmodel/abstract_item_view.hpp>
#include <ftxmodel/abstract_list_model.hpp>
#include <ftxmodel/abstract_proxy_model.hpp>
#include <ftxmodel/concat_proxy_model.hpp>
#include <ftxmodel/file_system_model.hpp>
#include <ftxmodel/flatten_tree_proxy_model.hpp>
#include <ftxmodel/header_decorators.hpp>
#include <ftxmodel/identity_proxy_model.hpp>
#include <ftxmodel/item_delegate.hpp>
#include <ftxmodel/item_selection_model.hpp>
#include <ftxmodel/join_proxy_model.hpp>
#include <ftxmodel/list_view.hpp>
#include <ftxmodel/proxy_item_delegate.hpp>
#include <ftxmodel/scrollable_tree_view.hpp>
#include <ftxmodel/shortcut_action_model.hpp>
#include <ftxmodel/shortcut_bar.hpp>
#include <ftxmodel/sort_filter_proxy_model.hpp>
#include <ftxmodel/standard_item_model.hpp>
#include <ftxmodel/string_list_model.hpp>
#include <ftxmodel/table_view.hpp>
#include <ftxmodel/tree_table_model.hpp>
#include <ftxmodel/tree_view.hpp>
#include <ftxmodel/vector_table_model.hpp>
#include "mock_item_model.hpp"
