function(AddExample Source)
    get_filename_component(base_source "${Source}" NAME_WE)
    add_executable(${base_source} ${Source})
    target_link_libraries(${base_source} PRIVATE ftxmodel)
    target_compile_features(${base_source} PRIVATE cxx_std_20)
    target_compile_options(${base_source} PRIVATE -Wall -Werror -Wextra -Wconversion -Wsign-conversion)
endfunction()

AddExample(list_view_app.cpp)
AddExample(table_view_app.cpp)
AddExample(tree_view_app.cpp)
AddExample(task_view_tree_app.cpp)
AddExample(fs_model_app.cpp)
AddExample(multi_router_delegate_app.cpp)
AddExample(format_text_app.cpp)
AddExample(flatten_model.cpp)
AddExample(contact_proxy_model_app.cpp)